using System;
using System.Collections.Generic;

namespace Re4QuadExtremeEditor.src.Class.Files
{
    /// <summary><para>RE4 item/key name database used by the AVL Key ID dropdown;</para><para>extracted from the reference AVL editor tool;</para></summary>
    public static class AVL_ItemNames
    {
        public static readonly Dictionary<ushort, string> List = new Dictionary<ushort, string>()
        {
            { 0x0000, "Magnum Ammo" },
            { 0x0001, "Hand Grenade" },
            { 0x0002, "Incendiary Grenade" },
            { 0x0003, "Matilda" },
            { 0x0004, "Handgun Ammo" },
            { 0x0005, "First Aid Spray" },
            { 0x0006, "Green Herb" },
            { 0x0007, "Rifle Ammo" },
            { 0x0008, "Chicken Egg" },
            { 0x0009, "Brown Chicken Egg" },
            { 0x000A, "Gold Chicken Egg" },
            { 0x000B, "[CRASHES GAME] aaa" },
            { 0x000C, "Plaga Sample" },
            { 0x000D, "[CRASHES GAME] Krauser's Knife" },
            { 0x000E, "Flash Grenade" },
            { 0x000F, "Salazar Family Insignia" },
            { 0x0010, "Bowgun (TO ADA)" },
            { 0x0011, "Bowgun Bolts" },
            { 0x0012, "Green Herb (x2)" },
            { 0x0013, "Green Herb (x3)" },
            { 0x0014, "Mixed Herbs (G+R)" },
            { 0x0015, "Mixed Herbs (G+R+Y)" },
            { 0x0016, "Mixed Herbs (G+Y)" },
            { 0x0017, "Rocket Launcher (Special)" },
            { 0x0018, "Shotgun Shells" },
            { 0x0019, "Red Herb" },
            { 0x001A, "Handcannon Ammo" },
            { 0x001B, "Hourglass with gold decor" },
            { 0x001C, "Yellow Herb" },
            { 0x001D, "Stone Tablet" },
            { 0x001E, "Lion Ornament" },
            { 0x001F, "Goat Ornament" },
            { 0x0020, "TMP Ammo" },
            { 0x0021, "Punisher" },
            { 0x0022, "[CRASHES GAME] Punisher w/ Silencer" },
            { 0x0023, "Handgun" },
            { 0x0024, "[CRASHES GAME] Handgun w/ Silencer" },
            { 0x0025, "Red9" },
            { 0x0026, "[CRASHES GAME] Red9 w/ Stock" },
            { 0x0027, "Blacktail" },
            { 0x0028, "[CRASHES GAME] Blacktail w/ Silencer" },
            { 0x0029, "Broken Butterfly" },
            { 0x002A, "Killer7" },
            { 0x002B, "[CRASHES GAME] Killer7 w/ Silencer" },
            { 0x002C, "Shotgun" },
            { 0x002D, "Striker" },
            { 0x002E, "Rifle" },
            { 0x002F, "Rifle (semi-auto)" },
            { 0x0030, "TMP" },
            { 0x0031, "Activation Key (blue)" },
            { 0x0032, "[CRASHES GAME] Tmp W/ Stock" },
            { 0x0033, "Activation Key (red)" },
            { 0x0034, "Chicago Typewriter" },
            { 0x0035, "Rocket Launcher" },
            { 0x0036, "Mine Thrower" },
            { 0x0037, "Handcannon" },
            { 0x0038, "[CRASHES GAME] Combat Knife" },
            { 0x0039, "Serpent Ornament" },
            { 0x003A, "Moonstone (Right Half)" },
            { 0x003B, "Insignia Key" },
            { 0x003C, "Round Insignia" },
            { 0x003D, "False Eye" },
            { 0x003E, "Custom TMP" },
            { 0x003F, "Silencer (Handgun)" },
            { 0x0040, "Ada Punisher" },
            { 0x0041, "P.R.L. 412" },
            { 0x0042, "Stock (Red9)" },
            { 0x0043, "Stock (TMP)" },
            { 0x0044, "Scope (Rifle)" },
            { 0x0045, "Scope (semi-auto rifle)" },
            { 0x0046, "Mine-Darts" },
            { 0x0047, "Ada Shotgun" },
            { 0x0048, "[FILE DOCUMENT] Capture Luis Sera" },
            { 0x0049, "[FILE DOCUMENT] Target Practice" },
            { 0x004A, "[FILE DOCUMENT] Luis' Memo" },
            { 0x004B, "[FILE DOCUMENT] Castellan Memo" },
            { 0x004C, "[FILE DOCUMENT] Female Intruder" },
            { 0x004D, "[FILE DOCUMENT] Butler's Memo" },
            { 0x004E, "[FILE DOCUMENT] Sample Retrieved" },
            { 0x004F, "[FILE DOCUMENT] Ritual Preparation" },
            { 0x0050, "[FILE DOCUMENT] Luis' Memo 2" },
            { 0x0051, "[CRASHES GAME] Rifle (semi-auto) w/ Infrared Scope" },
            { 0x0052, "Krauser's Bow" },
            { 0x0053, "Chicago Typewriter (Mafia version)" },
            { 0x0054, "[UNOBTAINABLE] Treasure Map (Castle)" },
            { 0x0055, "[UNOBTAINABLE] Treasure Map (Island)" },
            { 0x0056, "Velvet Blue" },
            { 0x0057, "Spinel" },
            { 0x0058, "Pearl Pendant" },
            { 0x0059, "Brass Pocket Watch" },
            { 0x005A, "Elegant Headdress" },
            { 0x005B, "Antique Pipe" },
            { 0x005C, "Gold Bangle with Pearls" },
            { 0x005D, "Amber Ring" },
            { 0x005E, "Beerstein" },
            { 0x005F, "Green Catseye" },
            { 0x0060, "Red Catseye" },
            { 0x0061, "Yellow Catseye" },
            { 0x0062, "Beerstein w/ (G)" },
            { 0x0063, "Beerstein w/ ( R )" },
            { 0x0064, "Beerstein w/ (Y)" },
            { 0x0065, "Beerstein w/ (G,R)" },
            { 0x0066, "Beerstein w/ (G,Y)" },
            { 0x0067, "Beerstein w/ (R,Y)" },
            { 0x0068, "Beerstein w/ (G,R,Y)" },
            { 0x0069, "Moonstone (Left Half)" },
            { 0x006A, "Chicago Typewriter Ammo" },
            { 0x006B, "[CRASHES GAME] Rifle + Scope" },
            { 0x006C, "[CRASHES GAME] Rifle (semi-auto) w/ Scope" },
            { 0x006D, "Infinite Rocket Launcher" },
            { 0x006E, "King's Grail" },
            { 0x006F, "Queen's Grail" },
            { 0x0070, "Staff Of Royalty" },
            { 0x0071, "Gold Bars" },
            { 0x0072, "Arrows" },
            { 0x0073, "Bonus Time" },
            { 0x0074, "Emergency Lock Card Key" },
            { 0x0075, "Bonus Points" },
            { 0x0076, "Green Catseye" },
            { 0x0077, "Ruby" },
            { 0x0078, "Treasure Box (S)" },
            { 0x0079, "Treasure Box (L)" },
            { 0x007A, "Blue Moonstone" },
            { 0x007B, "Key to the Mine" },
            { 0x007C, "[UNOBTAINABLE] Attache Case S" },
            { 0x007D, "[UNOBTAINABLE] Attache Case M" },
            { 0x007E, "[UNOBTAINABLE] Attache Case L" },
            { 0x007F, "[UNOBTAINABLE] Attache Case XL" },
            { 0x0080, "Golden Sword" },
            { 0x0081, "Iron Key" },
            { 0x0082, "Stone of Sacrifice" },
            { 0x0083, "Storage Room Card Key" },
            { 0x0084, "Freezer Card Key" },
            { 0x0085, "Piece of the Holy Beast, Panther" },
            { 0x0086, "Piece of the Holy Beast, Serpent" },
            { 0x0087, "Piece of the Holy Beast, Eagle" },
            { 0x0088, "Jet-ski Key" },
            { 0x0089, "Dirty Pearl Pendant" },
            { 0x008A, "Dirty Brass Pocket Watch" },
            { 0x008B, "Old Key" },
            { 0x008C, "Camp Key" },
            { 0x008D, "Dynamite" },
            { 0x008E, "Lift Activation Key" },
            { 0x008F, "Gold Bangle" },
            { 0x0090, "Elegant Perfume Bottle" },
            { 0x0091, "Mirror w/ Pearls & Rubies" },
            { 0x0092, "Waste Disposal Card Key" },
            { 0x0093, "Elegant Chessboard" },
            { 0x0094, "Riot Gun" },
            { 0x0095, "Black Bass" },
            { 0x0096, "Hourglass w/ gold decor" },
            { 0x0097, "Black Bass (L)" },
            { 0x0098, "Illuminados Pendant" },
            { 0x0099, "[CRASHES GAME] Rifle w/ Infrared Scope" },
            { 0x009A, "Crown" },
            { 0x009B, "Crown Jewel" },
            { 0x009C, "Royal Insignia" },
            { 0x009D, "Crown with Jewels" },
            { 0x009E, "Crown with an insignia" },
            { 0x009F, "Salazar Family Crown" },
            { 0x00A0, "[DOES NOT WORK] Rifle Ammo (Infrared)" },
            { 0x00A1, "Emerald" },
            { 0x00A2, "Bottle Caps (TREASURE)" },
            { 0x00A3, "Gallery Key" },
            { 0x00A4, "Emblem (Right half)" },
            { 0x00A5, "Emblem (Left half)" },
            { 0x00A6, "Hexagonal Emblem (Key Item)" },
            { 0x00A7, "Castle Gate Key" },
            { 0x00A8, "Mixed Herbs (R+Y)" },
            { 0x00A9, "[UNOBTAINABLE] Treasure Map (Village)" },
            { 0x00AA, "Scope (Mine Thrower)" },
            { 0x00AB, "[CRASHES GAME] Mine Thrower + Scope" },
            { 0x00AC, "[FILE DOCUMENT] Playing Manual 1" },
            { 0x00AD, "[FILE DOCUMENT] Info on Ashley" },
            { 0x00AE, "[FILE DOCUMENT] Playing Manual 2" },
            { 0x00AF, "[FILE DOCUMENT] Alert Order" },
            { 0x00B0, "[FILE DOCUMENT] About the Blue Medallions" },
            { 0x00B1, "[FILE DOCUMENT] Chief's Note" },
            { 0x00B2, "[FILE DOCUMENT] Closure of the Church" },
            { 0x00B3, "[FILE DOCUMENT] Anonymous Letter" },
            { 0x00B4, "[FILE DOCUMENT] Playing Manual 3" },
            { 0x00B5, "[FILE DOCUMENT] Sera and the 3rd Party" },
            { 0x00B6, "[FILE DOCUMENT] Two Routes" },
            { 0x00B7, "[FILE DOCUMENT] Village's Last Defense" },
            { 0x00B8, "Butterfly Lamp" },
            { 0x00B9, "Green Eye" },
            { 0x00BA, "Red Eye" },
            { 0x00BB, "Blue Eye" },
            { 0x00BC, "Butterfly Lamp w/ (G)" },
            { 0x00BD, "Butterfly Lamp w/ ( R )" },
            { 0x00BE, "Butterfly Lamp w/ (B)" },
            { 0x00BF, "Butterfly Lamp w/ (G,R)" },
            { 0x00C0, "Butterfly Lamp w/ (G,B)" },
            { 0x00C1, "Butterfly Lamp w/ (R,B)" },
            { 0x00C2, "Butterfly Lamp w/ (R,G,B)" },
            { 0x00C3, "Prison Key" },
            { 0x00C4, "Platinum Sword" },
            { 0x00C5, "Infrared Scope" },
            { 0x00C6, "Elegant Mask" },
            { 0x00C7, "Green Gem" },
            { 0x00C8, "Red Gem" },
            { 0x00C9, "Purple Gem" },
            { 0x00CA, "Elegant Mask w/ (G)" },
            { 0x00CB, "Elegant Mask w/ (R)" },
            { 0x00CC, "Elegant Mask w/ (P)" },
            { 0x00CD, "Elegant Mask w/ (G,R)" },
            { 0x00CE, "Elegant Mask w/ (G,P)" },
            { 0x00CF, "Elegant Mask w/ (R,P)" },
            { 0x00D0, "Elegant Mask w/ (R,G,P)" },
            { 0x00D1, "Golden Lynx" },
            { 0x00D2, "Green Stone of Judgement" },
            { 0x00D3, "Red Stone of Faith" },
            { 0x00D4, "Blue Stone of Treason" },
            { 0x00D5, "Golden Lynx w/ (G)" },
            { 0x00D6, "Golden Lynx w/ (R)" },
            { 0x00D7, "Golden Lynx w/ (B)" },
            { 0x00D8, "Golden Lynx w/ (G,R)" },
            { 0x00D9, "Golden Lynx w/ (G,B)" },
            { 0x00DA, "Golden Lynx w/ (R,B)" },
            { 0x00DB, "Golden Lynx w/ (G,R,B)" },
            { 0x00DC, "[UNOBTAINABLE] [BOTTLE CAP] Leon w/ rocket launcher" },
            { 0x00DD, "[UNOBTAINABLE] [BOTTLE CAP] Leon w/ shotgun" },
            { 0x00DE, "[UNOBTAINABLE] [BOTTLE CAP] Leon w/ handgun" },
            { 0x00DF, "[UNOBTAINABLE] [BOTTLE CAP] Ashley Graham" },
            { 0x00E0, "[UNOBTAINABLE] [BOTTLE CAP] Luis Sera" },
            { 0x00E1, "[UNOBTAINABLE] [BOTTLE CAP] Don Jose" },
            { 0x00E2, "[UNOBTAINABLE] [BOTTLE CAP] Don Diego" },
            { 0x00E3, "[UNOBTAINABLE] [BOTTLE CAP] Don Esteban" },
            { 0x00E4, "[UNOBTAINABLE] [BOTTLE CAP] Don Manuel" },
            { 0x00E5, "[UNOBTAINABLE] [BOTTLE CAP] Dr. Salvador" },
            { 0x00E6, "[UNOBTAINABLE] [BOTTLE CAP] Merchant" },
            { 0x00E7, "[UNOBTAINABLE] [BOTTLE CAP] Zealot w/ scythe" },
            { 0x00E8, "[UNOBTAINABLE] [BOTTLE CAP] Zealot w/ shield" },
            { 0x00E9, "[UNOBTAINABLE] [BOTTLE CAP] Zealot w/ bowgun" },
            { 0x00EA, "[UNOBTAINABLE] [BOTTLE CAP] Leader zealot" },
            { 0x00EB, "[UNOBTAINABLE] [BOTTLE CAP] Soldier w/ dynamite" },
            { 0x00EC, "[UNOBTAINABLE] [BOTTLE CAP] Soldier w/ stun-rod" },
            { 0x00ED, "[UNOBTAINABLE] [BOTTLE CAP] Soldier w/ hammer" },
            { 0x00EE, "[UNOBTAINABLE] [BOTTLE CAP] Isabel" },
            { 0x00EF, "[UNOBTAINABLE] [BOTTLE CAP] Maria" },
            { 0x00F0, "[UNOBTAINABLE] [BOTTLE CAP] Ada Wong" },
            { 0x00F1, "[UNOBTAINABLE] [BOTTLE CAP] Bella Sisters" },
            { 0x00F2, "[UNOBTAINABLE] [BOTTLE CAP] Don Pedro" },
            { 0x00F3, "[UNOBTAINABLE] [BOTTLE CAP] J.J." },
            { 0x00F4, "[FILE DOCUMENT] Letter from Ada" },
            { 0x00F5, "[FILE DOCUMENT] Luis' Memo 3" },
            { 0x00F6, "[FILE DOCUMENT] Paper Airplane" },
            { 0x00F7, "[FILE DOCUMENT] Our Plan" },
            { 0x00F8, "[FILE DOCUMENT] Luis' Memo 4" },
            { 0x00F9, "[FILE DOCUMENT] Krauser's Note" },
            { 0x00FA, "[FILE DOCUMENT] Luis' Memo 5" },
            { 0x00FB, "[FILE DOCUMENT] Our Mission" },
            { 0x00FC, "[CRASHES GAME] aaa" },
            { 0x00FD, "[CRASHES GAME] aaa" },
            { 0x00FE, "Tactical Vest" },
            { 0x00FF, "[CRASHES GAME] aaa" },
            { 0x0100, "[CRASHES GAME] Punisher" },
            { 0x0101, "[CRASHES GAME] Handgun" },
            { 0x0102, "[CRASHES GAME] Shotgun" },
            { 0x0103, "[CRASHES GAME] Mine Thrower" },
            { 0x0104, "[CRASHES GAME] Handcannon" },
            { 0x0105, "[CRASHES GAME] Mine Thrower + Scope" },
            { 0x0106, "[SEPARATE WAYS] Mission Directives 1" },
            { 0x0107, "[SEPARATE WAYS] Mission Directives 2" },
            { 0x0108, "[SEPARATE WAYS] Mission Directives 3" },
            { 0x0109, "[SEPARATE WAYS] Mission Directives 4" },
            { 0x010A, "[SEPARATE WAYS] Mission Directives 5" },
            { 0x010B, "[SEPARATE WAYS] Mission 1 Treasure Map" },
            { 0x010C, "[SEPARATE WAYS] Mission 2 Treasure Map" },
            { 0x010D, "[SEPARATE WAYS] Mission 3 Treasure Map" },
            { 0x010E, "[SEPARATE WAYS] Mission 4 Treasure Map" },
            { 0x010F, "[SEPARATE WAYS] Mission 5 Treasure Map" },
            { 0x1000, "SNAKE IN BOX" },
            { 0x1001, "RANDOM ITEM" },
            { 0x1002, "RANDOM ITEM" },
            { 0x1003, "RANDOM ITEM" },
            { 0x1004, "RANDOM ITEM" },
            { 0x1005, "RANDOM ITEM" },
            { 0xFFFF, "" },
        };

        /// <summary>retorna o nome do item ou null se desconhecido;</summary>
        public static string GetName(ushort id)
        {
            string name;
            if (List.TryGetValue(id, out name) && name.Length > 0)
            {
                return name;
            }
            return null;
        }
    }
}
